default: &default
  adapter: postgresql
  encoding: unicode
  host: database_travail
  username: postgres
  pool: 30

development:
  <<: *default
  database: travail_development

test:
  <<: *default
  database: travail_test
