default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database_travail
  username: postgres
  password: 

development:
  <<: *default
  database: travail_development

test:
  <<: *default
  database: travail_test
